services:

  prometheus:
    volumes:
      - ./node-exporter/prometheus-scrape.yml:/etc/prometheus/scrape_configs/node-exporter-scrape.yml:ro
    extra_hosts:
      - "watchdog-node-exporter:172.17.0.1"
      - "localip-node-exporter:172.17.0.1" 

